### ISSUE TITLE
Support for pandoc-gls / pandoc-ac style commands

### ISSUE THREAD

**Issue by marvin-te** [MalteHei/latex-acronyms#2]
I am using Pandoc to write my documents in Markdown, which converts them to LaTeX and then PDF and is actually a widely used tool.

To reference my glossary entries and acronyms I am using [pandoc-gls](https://github.com/tomncooper/pandoc-gls), which introduces an easyier syntax than `\acrshort{}` or similar. The glossary entries themselves are written in a normal LaTeX file though.

You currently have the option to make your plugin work with custom LaTeX commands, but you still require the `\somethingsomething{acr}` syntax (the backslash and curly brackets). I would love to use your plugin with the [pandoc-gls](https://github.com/tomncooper/pandoc-gls) syntax (i.e. `(+acr)`). It would be awesome if you could add this functionality.

Cheers.

**Comment by MalteHei** [comment]
Thanks for the suggestion!
Sadly, I don't think this fits the scope of this extension. My intention was to create small, modular and LaTeX-related extensions.

Though feel free to fork this repository and change the code to meet your needs!
